### ISSUE TITLE
Problems during the compiling process.

### ISSUE THREAD

**Issue by xuhenry** [HydroComplexity/Dhara#28]
Dear authors,
    I'm compiling the Dhara which I'm very interesting for the simulation of the surface and subsurface flow. But I met some problems during the compiling process, as follows:

In file included from ./include/cusplibrary-0.5.1/cusp/system/cuda/detail/multiply/coo_flat_spmv.h:21:0,
                 from ./include/cusplibrary-0.5.1/cusp/system/cuda/detail/multiply.h:21,
                 from ./include/cusplibrary-0.5.1/cusp/system/cuda/execution_policy.h:50,
                 from ./include/cusplibrary-0.5.1/cusp/execution_policy.h:34,
                 from ./include/cusplibrary-0.5.1/cusp/convert.h:25,
                 from ./include/cusplibrary-0.5.1/cusp/detail/coo_matrix.inl:18,
                 from ./include/cusplibrary-0.5.1/cusp/coo_matrix.h:605,
                 from src/../include/cusplib.h:7,
                 from src/subsurface.cu:14:
./include/cusplibrary-0.5.1/cusp/system/cuda/arch.h:24:64: fatal error: thrust/system/cuda/detail/detail/launch_calculator.h: No such file or directory
 #include <thrust/system/cuda/detail/detail/launch_calculator.h>
                                                                ^
compilation terminated.
Makefile:45: recipe for target 'src/obj/subsurface.cu.o' failed
make: *** [src/obj/subsurface.cu.o] Error 1

I can't fix them. I'm very glad if you can help me to fix them.
Thanks a lot!
Best regards,
Henry

**Comment by levuvietphong** [comment]
Hi Henry,

It seems that the compiler couldn't load the launch_calculator.h header file from your cuda (Fatal error: thrust/system/cuda/detail/detail/launch_calculator.h: No such file or directory). 

This is from the Thrust library (https://thrust.github.io/). Please check if your thrust library works properly first (See here https://docs.nvidia.com/cuda/thrust/index.html). 

Also, what is the OS and CUDA driver version you are using?

Thanks

**Comment by xuhenry** [comment]
Dear Phong,
    Many thanks for your help. I have fixed this problem. But now I meet another problem, as follows. I'm using the Ubunutu18.04 and Cuda 9.1. Thanks a lot!
    

tmpxft_00003670_00000000-5_global.compute_35.cudafe1.cpp:(.text.startup+0xf5): undefined reference to `__cudaRegisterFunction'
src/obj/global.cu.o:tmpxft_00003670_00000000-5_global.compute_35.cudafe1.cpp:(.text.startup+0x123): more undefined references to `__cudaRegisterFunction' follow
src/obj/global.cu.o: In function `__sti____cudaRegisterAll()':
tmpxft_00003670_00000000-5_global.compute_35.cudafe1.cpp:(.text.startup+0x14d): undefined reference to `__cudaRegisterVar'
tmpxft_00003670_00000000-5_global.compute_35.cudafe1.cpp:(.text.startup+0x175): undefined reference to `__cudaRegisterVar'
tmpxft_00003670_00000000-5_global.compute_35.cudafe1.cpp:(.text.startup+0x19d): undefined reference to `__cudaRegisterVar'
tmpxft_00003670_00000000-5_global.compute_35.cudafe1.cpp:(.text.startup+0x1c6): undefined reference to `__cudaRegisterVar'
tmpxft_00003670_00000000-5_global.compute_35.cudafe1.cpp:(.text.startup+0x1f0): undefined reference to `__cudaRegisterVar'
src/obj/global.cu.o:tmpxft_00003670_00000000-5_global.compute_35.cudafe1.cpp:(.text.startup+0x219): more undefined references to `__cudaRegisterVar' follow
collect2: error: ld returned 1 exit status
Makefile:51: recipe for target 'bin/dhara' failed
make: *** [bin/dhara] Error 1

Best regards,
Henry

**Comment by levuvietphong** [comment]
Hi Henry,

I am not sure, but it looks like there is a linking problem here. This is probably related to the hardware (compute capability) of your GPU device, not Dhara code.
Could you send me some information on your device?

**Comment by xuhenry** [comment]
Dear Phong,
    Maybe there are some problems about the hardware. The GPU card is Tesla C2050.  I'm trying to find the errors.
Thanks a lot!
Best regards,
Henry
