### ISSUE TITLE
paper question

### ISSUE THREAD

**Issue by zjin-lcf** [HydroComplexity/Dhara#29]
which of your papers describes the function "void vanGenuchten ()" ?   Thanks.

// Compute the volumetric moisture content [eqn 21]
// Compute the effective saturation [eqn 2]
...

**Comment by levuvietphong** [comment]
The vanGenchten function is developed based on the following paper:
A Closed-form Equation for Predicting the Hydraulic Conductivity of Unsaturated Soils
(https://acsess.onlinelibrary.wiley.com/doi/10.2136/sssaj1980.03615995004400050002x#FN1)
